services:
  postgres17:
    image: postgres:17
    restart: unless-stopped
    container_name: postgrestest
    # we disable a few options to make the database faster for testing
    # this options should not be used on production
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c max_connections=500
    environment:
      POSTGRES_PASSWORD: root
    healthcheck:
      test: pg_isready -U postgres
    ports:
      - 55432:5432